name: Compile & Release
on: push
jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
      - name: Install Noto fonts
        run: sudo apt-get install -y fonts-noto-core
      - run: typst compile otazky.typ otazky.pdf
      - name: Set release date
        id: date
        run: |
          echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
          echo "display=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ steps.date.outputs.timestamp }}
          name: ${{ steps.date.outputs.display }}
          files: otazky.pdf
          generate_release_notes: true
